---
version: 2.1
description: |
  A collection of useful Puppet commands, executors and jobs for doing CI/CD.

  See https://github.com/broadinstitute/circleci-orb-bits-puppet

commands:
  prereq:
    description: 'Install and cache all dependencies including any unit test fixtures'
    parameters:
      cache_version:
        description: 'A cache version that may be used for cache busting'
        type: string
        default: 'v1'
  prereq-pdk:
    description: 'Install and cache all dependencies including any unit test fixtures (pdk)'
    parameters:
      cache_version:
        description: 'A cache version that may be used for cache busting'
        type: string
        default: 'v1'
    steps:
      - restore_cache:
          key: <<parameters.cache_version>>-pdk-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ checksum "Gemfile" }}-{{ .Environment.CIRCLE_JOB }}
      - run:
          name: 'Install PDK'
          command: |
            mkdir -p ~/.config/puppet
            cp .circleci/analytics.yml ~/.config/puppet/analytics.yml
            curl -o /tmp/puppet.deb https://apt.puppet.com/puppet-tools-release-stretch.deb
            sudo dpkg -i /tmp/puppet.deb
            sudo apt-get update
            sudo apt-get install pdk
      - run:
          name: 'Install Puppet dependencies'
          command: |
            rm -f Gemfile.lock
            pdk bundle
      - run:
          name: 'Install fixtures'
          command: bundle exec rake spec_prep
      - save_cache:
          key: <<parameters.cache_version>>-pdk-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ checksum "Gemfile" }}-{{ .Environment.CIRCLE_JOB }}
          paths:
            - '/opt/puppetlabs/pdk/share/cache/ruby'
  publish:
    description: 'Publish the module to the Forge'
    steps:
      - run:
          name: 'Build module'
          command: 'bundle exec rake build'
      - run:
          name: 'Publishing module to PuppetForge'
          command: 'bundle exec rake module:push'
          environment:
            BLACKSMITH_FORGE_URL: 'https://forgeapi.puppet.com'
  publish-pdk:
    description: 'Publish the module to the Forge (pdk)'
    steps:
      - run:
          name: 'Build module'
          command: 'pdk build'
      - run:
          name: 'Publishing module to PuppetForge'
          command: 'pdk release publish'
          environment:
            BLACKSMITH_FORGE_URL: 'https://forgeapi.puppet.com'
  static:
    description: 'Run all static analysis'
    steps:
      - run:
          name: 'Symlink check'
          command: 'bundle exec rake check:symlinks'
      - run:
          name: '.gitignore check'
          command: 'bundle exec rake check:git_ignore'
      - run:
          name: 'dot_underscore check'
          command: 'bundle exec rake check:dot_underscore'
      - run:
          name: 'test file check'
          command: 'bundle exec rake check:test_file'
      - run:
          name: 'RuboCop check'
          command: 'bundle exec rake rubocop'
      - run:
          name: 'Syntax check'
          command: 'bundle exec rake syntax'
      - run:
          name: 'Lint check'
          command: 'bundle exec rake lint'
      - run:
          name: 'Metadata lint check'
          command: 'bundle exec rake metadata_lint'
  static-pdk:
    description: 'Run all static analysis (pdk)'
    steps:
      - run:
          name: 'PDK Validator'
          command: 'pdk validate --parallel'
  unit-tests:
    description: 'Run Puppet unit tests'
    steps:
      - run:
          name: 'Run unit tests'
          command: 'bundle exec rake spec'
  unit-tests-pdk:
    description: 'Run Puppet unit tests (pdk)'
    steps:
      - run:
          name: 'Run unit tests'
          command: 'pdk test unit --parallel --verbose'
  verify-tag:
    description: 'Verify the internal version vs. the git tag'
    steps:
      - run:
          name: 'Verify git tag vs. metadata version'
          command: |
            bash -c 'CIRCLE_TAG=${CIRCLE_TAG:-XXX} && [ $CIRCLE_TAG == $( cat metadata.json | jq -r '.version' ) ]'
executors:
  ruby_puppet:
    parameters:
      puppet_version:
        type: 'string'
        default: '< 6.0.0'
      resource_class:
        type: 'string'
        default: 'small'
      ruby_version:
        type: 'string'
        default: '2.4.6'
    docker:
      - image: circleci/ruby:<< parameters.ruby_version >>
    environment:
      PUPPET_GEM_VERSION: << parameters.puppet_version >>
    resource_class: << parameters.resource_class >>
    working_directory: '/tmp/build'
jobs:
  deploy:
    description: 'Deploy to Puppet Forge'
    parameters:
      resource_class:
        type: 'string'
        default: 'small'
      use_pdk:
        default: false
        type: boolean
    executor:
      name: 'ruby_puppet'
      puppet_version: '< 6.0.0'
      resource_class: << parameters.resource_class >>
      ruby_version: '2.4.6'
    steps:
      - 'checkout'
      - when:
        condition: << parameters.use_pdk >>
        steps:
          - prereq-pdk
      - unless:
        condition: << parameters.use_pdk >>
        steps:
          - prereq
      - 'verify-tag'
      - when:
        condition: << parameters.use_pdk >>
        steps:
          - publish-pdk
      - unless:
        condition: << parameters.use_pdk >>
        steps:
          - publish
  run-tests:
    description: 'Run all tests'
    parameters:
      puppet_version:
        type: 'string'
        default: '< 6.0.0'
      resource_class:
        type: 'string'
        default: 'small'
      ruby_version:
        type: 'string'
        default: '2.4.6'
      use_pdk:
        default: false
        type: boolean
    executor:
      name: 'ruby_puppet'
      puppet_version: << parameters.puppet_version >>
      resource_class: << parameters.resource_class >>
      ruby_version: << parameters.ruby_version >>
    steps:
      - 'checkout'
      - when:
        condition: << parameters.use_pdk >>
        steps:
          - prereq-pdk
      - unless:
        condition: << parameters.use_pdk >>
        steps:
          - prereq
      - when:
        condition: << parameters.use_pdk >>
        steps:
          - unit-tests-pdk
      - unless:
        condition: << parameters.use_pdk >>
        steps:
          - unit-tests
  static:
    description: 'Run all static analysis'
    parameters:
      resource_class:
        type: 'string'
        default: 'small'
      use_pdk:
        default: false
        type: boolean
    executor:
      name: 'ruby_puppet'
      puppet_version: '< 6.0.0'
      resource_class: << parameters.resource_class >>
      ruby_version: '2.4.6'
    steps:
      - 'checkout'
      - when:
        condition: << parameters.use_pdk >>
        steps:
          - prereq-pdk
      - unless:
        condition: << parameters.use_pdk >>
        steps:
          - prereq
      - when:
        condition: << parameters.use_pdk >>
        steps:
          - static-pdk
      - unless:
        condition: << parameters.use_pdk >>
        steps:
          - static
